FROM openjdk:17-jdk-slim

WORKDIR /app
COPY ./target/bakalarka_szathmary-1.0.0.jar /app

ENV MYSQL_BAKALARKA_URL=${MYSQL_BAKALARKA_URL}
ENV MYSQL_BAKALARKA_USERNAME=${MYSQL_BAKALARKA_USERNAME}
ENV MYSQL_BAKALARKA_PASSWORD=${MYSQL_BAKALARKA_PASSWORD}

ENV JWT_TOKEN=${JWT_TOKEN}

ENV INFLUX_DB_URL=${INFLUX_DB_URL}
ENV INFLUX_DB_TOKEN=${INFLUX_DB_TOKEN}
ENV INFLUX_DB_ORG=${INFLUX_DB_ORG}

EXPOSE 8080

CMD ["java", "-jar", "bakalarka_szathmary-1.0.0.jar"]